import { CurrencyDollar } from '@vicons/tabler';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const tool = defineTool({
  name: translate('tools.currency-converter.title'),
  path: '/currency-converter',
  description: translate('tools.currency-converter.description'),
  keywords: [
    'currency',
    'converter',
    'money',
    'exchange',
    'rate',
    'forex',
    'USD',
    'EUR',
    'GBP',
    'JPY',
    'CNY',
    'CAD',
    'AUD',
    'CHF',
    'INR',
    'RUB',
    'BRL',
    'MXN',
    'ZAR',
    'SGD',
    'HKD',
    'NOK',
    'SEK',
    'DKK',
    'NZD',
    'KRW',
    'TRY',
    'PLN',
    'CZK',
    'HUF',
    'ILS',
    'AED',
    'SAR',
    'THB',
    'MYR',
    'PHP',
    'VND'
  ],
  component: () => import('./currency-converter.vue'),
  icon: CurrencyDollar,
  createdAt: new Date(),
});
